import type { Metadata } from "next"
import Link from "next/link"
import { MarketingArticle } from "@/components/common/marketing-article"

export const metadata: Metadata = {
  title: "Documentation",
  description:
    "How the SaaS boilerplate is structured: apps, packages, environment variables, API conventions, database workflow, and local development.",
}

export default function DocsPage() {
  return (
    <MarketingArticle
      title="Documentation"
      description="A practical guide to this monorepo: what lives where, how to run it, and how to extend the API and database safely."
    >
      <h2>Overview</h2>
      <p>
        This starter combines a <strong>Next.js</strong> web app, a <strong>Hono</strong> API on Node, a{" "}
        <strong>Prisma</strong> database package, and shared TypeScript packages. Authentication is wired for{" "}
        <strong>Supabase Auth</strong> with cookie-friendly sessions on the API where applicable.
      </p>
      <p>
        Use this document as a map; replace product-specific copy and routes as your application grows.
      </p>

      <h2>Repository layout</h2>
      <ul>
        <li>
          <code>apps/web</code> — Next.js App Router UI, marketing pages, auth screens, and the authenticated
          dashboard.
        </li>
        <li>
          <code>apps/api</code> — Hono server with versioned routes under <code>/api/v1/...</code>, Zod + OpenAPI
          schemas, and thin handlers that delegate to services.
        </li>
        <li>
          <code>packages/database</code> — Prisma schema, migrations workflow, and generated client consumed by the
          API.
        </li>
        <li>
          <code>packages/types</code> — Shared constants and types (for example enums aligned with the API).
        </li>
      </ul>
      <p>
        Task orchestration uses <strong>pnpm</strong> workspaces and <strong>Turbo</strong> so builds and checks stay
        cached and predictable.
      </p>

      <h2>Environment variables</h2>
      <p>
        Keep secrets out of source control. Typical development uses root-level env files such as{" "}
        <code>.env.development</code> (exact names depend on your setup). At minimum you will need:
      </p>
      <ul>
        <li>
          <strong>Web</strong> — <code>NEXT_PUBLIC_API_URL</code> pointing at your running API (for example{" "}
          <code>http://localhost:3000</code>), plus Supabase public keys used by the browser client.
        </li>
        <li>
          <strong>API</strong> — Supabase URL and keys, JWT-related settings, database URLs, and CORS origins that match
          your web origin.
        </li>
        <li>
          <strong>Database package</strong> — <code>DATABASE_URL</code> and <code>DIRECT_URL</code> for Prisma
          (often the same host with different connection modes for hosted Postgres).
        </li>
      </ul>
      <p>
        Validate required variables at startup in small config modules rather than scattering raw{" "}
        <code>process.env</code> reads across handlers.
      </p>

      <h2>Local development</h2>
      <p>From the repository root, install dependencies, then start the apps you need:</p>
      <ul>
        <li>
          <code>pnpm install</code>
        </li>
        <li>
          Run the web app (default port may be <code>3001</code> in this project) and the API per your{" "}
          <code>package.json</code> scripts.
        </li>
        <li>
          Apply database schema changes through the <strong>database package scripts</strong> (for example migrate in
          development) so migration files are generated by Prisma, not edited by hand.
        </li>
      </ul>
      <p>
        Point <code>NEXT_PUBLIC_API_URL</code> at the API base URL your browser can reach, including during Docker or
        tunnel-based setups.
      </p>

      <h2>API conventions</h2>
      <p>
        Routes are auto-loaded from <code>apps/api/src/routes</code>. Each module exports a path (for example{" "}
        <code>/api/v1/health</code>) and a Hono app instance registered with <code>@hono/zod-openapi</code>.
      </p>
      <ul>
        <li>
          Request and response shapes live next to the code under <code>apps/api/src/schema/v1</code>.
        </li>
        <li>
          Business logic belongs in <code>services/</code> with Prisma and Supabase clients injected from the request
          context.
        </li>
        <li>
          Only specific URL patterns run the JWT authorization middleware; public routes (health, selected auth
          endpoints, marketing data) stay reachable without a session.
        </li>
      </ul>
      <p>
        When the API is running, interactive OpenAPI documentation is usually served at the <code>/docs</code> path on
        the API origin (confirm in your deployment). Use it to try requests and to share contracts with frontend
        teammates.
      </p>

      <h2>Database workflow</h2>
      <p>
        The Prisma schema in <code>packages/database/prisma/schema.prisma</code> is the source of truth for tables and
        enums. After you change the schema, create migrations using the scripts defined in{" "}
        <code>packages/database/package.json</code> so SQL remains consistent and reviewable in pull requests.
      </p>
      <p>
        Generated Prisma Client is imported from the <code>@repo/database</code> workspace package; do not commit
        generated client output from <code>node_modules</code>.
      </p>

      <h2>Authentication model</h2>
      <p>
        End users sign up and sign in through flows that talk to the API and Supabase. Access tokens may be delivered
        via HTTP-only cookies for browser clients, while the same API can accept <code>Authorization: Bearer</code>{" "}
        headers for programmatic clients.
      </p>
      <p>
        Protected routes should assume nothing about the user until the authorization middleware has attached{" "}
        <code>c.get(&quot;user&quot;)</code>; use small helpers to enforce roles when you add admin or billing
        surfaces.
      </p>

      <h2>Frontend routing</h2>
      <p>
        Marketing routes (home, documentation, legal pages) share a shell with the global navigation and footer.
        Authentication routes under <code>/auth/...</code> use focused layouts suitable for sign-in and recovery
        flows. Dashboard routes live behind authentication on the client and should call protected API endpoints for
        data.
      </p>

      <h2>Going to production</h2>
      <ul>
        <li>Set production environment variables for web and API, including exact cookie and CORS domains.</li>
        <li>Run database migrations as part of your deploy pipeline.</li>
        <li>Turn on structured logging and log sampling appropriate to your traffic.</li>
        <li>Review rate limits and bot protection for public write endpoints (for example community reviews).</li>
      </ul>

      <hr />

      <p>
        Return to the <Link href="/">home page</Link>, read the <Link href="/terms">terms of service</Link>, or review
        the <Link href="/privacy">privacy policy</Link>.
      </p>
    </MarketingArticle>
  )
}
