// Export all middleware for easy imports
export { authorization, requireRole } from './authorization.js'
export { corsMiddleware } from './cors.js'
export { errorHandler } from './error-handler.js'
export { compression } from './compress.js'
export { cookieMiddleware } from './cookie.js'
export { helmet } from './helmet.js'
export { removePoweredBy, requestLogger } from './sensible.js'
export { formBodyParser } from './formbody.js'
export { multipart } from './multipart.js'
export { urlData } from './url-data.js'
export { i18nMiddleware } from './i18next.js'
export { setRequestLanguage } from './set-request-language.js'
export { underPressure } from './under-pressure.js'
export { registerGlobalMiddlewares, registerAutoRoutes } from './autoloader.js'
export type { MiddlewareDefinition } from './types.js'

